---
title: "Class 04 Data Structures and Data Importing in R"
author: "Thurman Schreel"
date: "`r Sys.Date()`"
output:  
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Frames
```{r df}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

crashes_df = tibble::tibble(
  day     = names(crashes_by_day),
  crashes = crashes_by_day,
  busy    = crashes_by_day > 2000
)
crashes_df

dplyr::glimpse(crashes_df)      # equivalent to str() but prints neater
```

# Examining a Job Ad
```{r job_ad}
job = list(
  title   = "Research Data Scientist, Magic Eye",
  company = "Google",
  salary  = list(min = 147000, max = 210000)
)
dplyr::glimpse(job)

# 1. The company name.
company_name = job$company      # not a list
company_name_as_named_list = job[2]   # we typically do not want that answer, correct is above
# 2. The maximum salary.
job$salary$max
# 3. The maximum salary again, using only [[ ]].
job[[3]][2]
# 4. The names of the elements in job.
names(job)
```

# Subsetting

## Vectors

- You can subset by position (like a number) or by name if it is a named vector
- You can also pass a vector (e.g. logical condition, 2:4, or c( ) ) for subsetting the vector
```{r vectors}
crashes_by_day = c(2020, 2241, 2327, 2285, 2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")
crashes_by_day[2:4]                      # you can give consecutive numbers
crashes_by_day[c(1, 5)] 
crashes_by_day[c('Mon', 'Fri')]
```

# Ohio Jobs
```{r}
oh_jobs = readr::read_csv(file = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=IHLIDXUSOH&scale=left&cosd=2021-08-28&coed=2026-08-28&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Daily%2C%207-Day&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-09-02&revision_date=2026-09-02&nd=2020-02-01")
# when using base r (read.csv) to read csv comes out as a character for the date opposed to read_csv which returns a date

dplyr::glimpse(oh_jobs)

```


