---
title: "Class 08"
author: "Thurman Schreel"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    code_folding: show
    toc_float: true
    number_sections: true
    code_download: true
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cincy Crashes
```{r api_intro}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> cincy_crashes

```

# FRED
```{r}
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |> 
  httr2::req_perform() |> 
  httr2::resp_body_string() |> 
  jsonlite::fromJSON() ->  ohio_jobs

jobs_df = ohio_jobs[[13]]

# to get data from Sept 1, 2026

# (a) to get all data then filter the rows I want
## not the most efficient, but correct
# first turn date from character into date column
jobs_df |> 
  dplyr::mutate(
    date = lubridate::ymd(date)
  ) |> 
  dplyr::filter(date >= '2026-09-01') -> jobs_df_mod

# [b] use the API since it had observation_start

httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start ="2026-09-01"
  ) |> 
  httr2::req_perform() |> 
  httr2::resp_body_string() |> 
  jsonlite::fromJSON() ->  ohio_jobs_sep_2026

ohio_jobs_sep_2026_df = ohio_jobs_sep_2026$observations

```

# Get finished lecture from canvas
# USAJOBS API
```{r usajobs}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "schreetp@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_list

usa_df = usa_jobs_list$SearchResult$SearchResultItems


# index_data_analyst = jobs_small$title |> 
#  stringr::str_detect(pattern = 'Data Analyst|Data Analytics')
```


