---
title: "Class13"
author: "Thurman Schreel"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plane Crash Example
```{r}
year = 2025
crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')
crash_page = rvest::read_html(crash_url, encoding="ISO-8859-1")

# What we learned last class is that if I were to read this as an HTML table, I have no control on what goes into each column in the resulting data frame -- this makes cleaning it more challenging

crash_page |> rvest::html_elements("td:nth-child(1) > font > a") |> 
  rvest::html_text2() -> dates

crash_page |> rvest::html_elements("td:nth-child(2) > font") |> 
  rvest::html_text2() -> loc_op

#skipped col 3 - exactly similar for time purposes
crash_page |> rvest::html_elements("td:nth-child(4) > font") |> 
  rvest::html_text2() -> fatalities

df = data.frame(dates, loc = loc_op[-1], fatalities[-1]) |> 
  tidyr::separate(
    loc, into =c("location", "operator"), sep = "\n")
  ) |> 
  tidyr::separate(
    fatalities, into =c("plane_fatalities", "pass", "ground_fatalities")
  )
  



```

